# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/


version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "prepare"
  - "build"
  - "security_scan"
  - "push"
  - "Release"

steps:
  main_clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "codefresh-io/cf-gitops-controller"
    revision: "${{CF_BRANCH}}"
    git: "cf_github"
    stage: "prepare"

  export_version:
    title: Compare version
    stage: build
    image: codefresh/semver
    commands:
      - export CF_GITOPS_VERSION=$(cat ./installer/VERSION)
      - echo "Cf gitops version -> CF_GITOPS_VERSION "
      - cf_export VERSION=$CF_GITOPS_VERSION
    when:
      steps:
        - name: main_clone
          on:
            - success
      branch:
        only:
          - main

  create_git_tag:
    title: Push tag to git
    image: codefresh/cli
    stage: Release
    commands:
      - export OLD_ORIGIN=$(git remote get-url origin)
      - git remote rm origin
      - git remote add origin https://${{GITHUB_TOKEN}}@github.com/codefresh-io/cf-gitops-controller.git
      - git tag ${{VERSION}}
      - git push --tags
      - git remote rm origin
      - git remote add origin $OLD_ORIGIN
    fail_fast: false
    when:
      steps:
        - name: export_version
        - name: main_clone
      branch:
        only:
          - main

  release_binaries:
    title: Create release in Github with argo-agent CLI
    image: goreleaser/goreleaser:v0.124.1
    stage: Release
    fail_fast: false
    commands:
      - goreleaser release -f .goreleaser.yml --rm-dist --skip-validate # pre-release
    when:
      steps:
        - name: create_git_tag
          on:
            - finished
      branch:
        only:
          - main
