package cmd

import (
	"errors"
	"fmt"
	"github.com/codefresh-io/cf-gitops-controller/pkg/install"
	"github.com/codefresh-io/cf-gitops-controller/pkg/kube"
	"github.com/codefresh-io/cf-gitops-controller/pkg/logger"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"os"
	"os/user"
	"path"
)

var installCmdOptions = install.CmdOptions{}

var installCmd = &cobra.Command{
	Use:   "install",
	Short: "Install gitops codefresh",
	Long:  `Install gitops codefresh`,
	RunE: func(cmd *cobra.Command, args []string) error {
		kubeOptions := installCmdOptions.Kube
		kubeClient, err := kube.New(&kube.Options{
			ContextName:      kubeOptions.Context,
			Namespace:        kubeOptions.Namespace,
			PathToKubeConfig: kubeOptions.ConfigPath,
		})
		if err != nil {
			return err
		}

		namespaceIsExist, err := kubeClient.NamespaceExists()
		if namespaceIsExist != true {
			logger.Info(fmt.Sprintf("Creating namespace \"%s\"...", installCmdOptions.Kube.Namespace))
			err = kubeClient.CreateNamespace()
			if err != nil {
				msg := fmt.Sprintf("Can't create namespace \"%s\"", installCmdOptions.Kube.Namespace)
				//sendControllerInstalledEvent(FAILED, msg)
				return errors.New(msg)
			}
		}

		logger.Info(fmt.Sprint("Creating argocd resources..."))
		// @todo
		_ = kubeClient.CreateResources(installCmdOptions.ManifestPath)
		// cp.execSync(`kubectl apply -n "${namespace}" -f "${manifest}"`, { stdio: 'inherit' });

		logger.Info(fmt.Sprint("Changing service type to \"LoadBalancer\"..."))
		// @todo
		//cp.execSync(
		//            `kubectl patch svc argocd-server -n "${namespace}" -p '{"spec": {"type": "LoadBalancer"}}'`,
		//            { stdio: 'inherit' },
		//        );

		logger.Info(fmt.Sprint("Getting argocd ip address..."))
		//host = `https://${await promiseRetry(getExternalIp(namespace), { retries: 100, factor: 1, minTimeout: 5000 })}`;

		logger.Info(fmt.Sprint("Getting autogenerated password..."))
		//autogenerated = cp.execSync(
		//            `kubectl get pods -n "${namespace}" -l app.kubernetes.io/name=argocd-server -o name | cut -d'/' -f 2 | xargs echo -n`,
		//            { encoding: 'utf-8' },
		//        );

		logger.Info(fmt.Sprint("Getting argocd token..."))
		//const argocdToken = await rp({
		//            method: 'POST',
		//            uri: `${host}/api/v1/session`,
		//            body: {
		//                username: 'admin',
		//                password: autogenerated,
		//            },
		//            json: true,
		//        });

		logger.Info(fmt.Sprint("Updating admin password..."))
		//await rp({
		//            method: 'PUT',
		//            uri: `${host}/api/v1/account/password`,
		//            headers: {
		//                Authorization: `Bearer ${argocdToken.token}`,
		//            },
		//            body: {
		//                currentPassword: autogenerated,
		//                name: 'admin',
		//                newPassword: password,
		//            },
		//            json: true,
		//        });

		logger.Success(fmt.Sprint("Successfully installed codefresh gitops controller"))

		return nil
	},
}

func init() {
	rootCmd.AddCommand(installCmd)
	flags := installCmd.Flags()

	flags.StringVar(&installCmdOptions.Argo.Password, "set-argo-password", "", "Set password for admin user of new argocd installation")
	flags.StringVar(&installCmdOptions.Kube.Namespace, "kube-namespace", "", "Namespace in Kubernetes cluster")
	flags.StringVar(&installCmdOptions.ManifestPath, "install-manifest", "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml", "Url of argocd install manifest")

	var kubeConfigPath string
	currentUser, _ := user.Current()
	if currentUser != nil {
		kubeConfigPath = os.Getenv("KUBECONFIG")
		if kubeConfigPath == "" {
			kubeConfigPath = path.Join(currentUser.HomeDir, ".kube", "config")
		}
	}

	flags.StringVar(&installCmdOptions.Kube.ConfigPath, "kube-config-path", kubeConfigPath, "Path to kubeconfig file (default is $HOME/.kube/config)")
	flags.StringVar(&installCmdOptions.Kube.Context, "kube-context-name", viper.GetString("kube-context"), "Name of the kubernetes context on which Argo agent should be installed (default is current-context) [$KUBE_CONTEXT]")

}
